### PR TITLE
[IN PROGRESS] Update to mio 0.7 and tokio 0.3

### PR DESCRIPTION
**Pull request by witchof0x20**
This is my attempt at updating to mio 0.7, as referenced in #6 

This is likely not entirely correct, and I plan to go back over it some time this week. Putting it up as a PR to make it easier to see changes.

### CODE REVIEW

**Comment by witchof0x20** [comment]
Tested this using
main.rs
```rust
use futures::executor;
use futures::stream::StreamExt;
use std::thread;
use tokio_udev::{EventType, MonitorBuilder};

#[tokio::main]
async fn main() {
    let mut monitor = MonitorBuilder::new()
        .unwrap()
        .match_subsystem("usb")
        .unwrap()
        .listen()
        .unwrap();

    loop {
        if let Some(event) = monitor.next().await {
            println!("{}", event.event_type());
            for property in event.device().properties() {
                println!("{:?} = {:?}", property.name(), property.value());
            }
        }
    }
}
```

Cargo.toml:
```toml
futures = "0.3"
tokio-udev = {path = "../tokio-udev/tokio-udev"}
tokio = { version = "0.3", features = ["full"] }
```

and it works great

With tokio-udev from cargo, I actually get 
`thread 'main' panicked at 'there is no reactor running, must be called from the context of Tokio runtime'`
with this code. I haven't dug into making my example code work with instantiating the reactor yet.

I did some additional testing, and it seems this PR would also allow for bumping this project's tokio dependency to 0.3. There are no compilation errors, and the example code works.

**Comment by witchof0x20** [comment]
https://github.com/jeandudey/tokio-udev/blob/master/tokio-udev/examples/usb_hotplug.rs
works with this PR
It doesn't work with tokio 0.3 (not in this PR), but that's for a separate PR I think

**Comment by jeandudey** [comment]
@witchof0x20 did it not work with udev-rs@0.5? To merge #10 first and then merge the tokio update code (when done).

File: tokio-udev/src/lib.rs [hunk 1]
```diff
@@ -137,41 +137,40 @@ impl Stream for MonitorSocket {
...
-        match self.io.get_mut().next() {
-            Some(event) => Poll::Ready(Some(event)),
-            None => {
-                self.io
-                    .clear_read_ready(cx, mio::Ready::readable())
-                    .unwrap();
-                Poll::Pending
+    fn poll_receive(&mut self) -> Poll<Option<mio_udev::Event>> {
+        let mut events = Events::with_capacity(1);
+        self.poll.poll(&mut events, None).unwrap();
```
Comment (jeandudey) [inline tokio-udev/src/lib.rs]: I think here we may wait for [AsyncFd](https://github.com/tokio-rs/tokio/pull/2903) to land on a minor release version of tokio to use that functionality, to avoid allocating memory here and to reduce code to maintain.

If https://github.com/tokio-rs/tokio/pull/2903 doesn't get on a minor release then I'm fine with this being merged as it's the only solution to this problem.

**Comment by witchof0x20** [comment]
> @witchof0x20 did it not work with udev-rs@0.5? To merge #10 first and then merge the tokio update code (when done).

It works with udev-rs@0.5, I just split it up because that one is an easy merge, while this is a bit more complicated.

File: tokio-udev/src/lib.rs (hunk 1 above)
Comment (jeandudey) [reply tokio-udev/src/lib.rs]: @witchof0x20 [AsyncFd](https://docs.rs/tokio/0.3.2/tokio/io/unix/struct.AsyncFd.html) landed on 0.3.2, feel free to update the code with:

```toml
tokio = { version = ">=0.3.2", features = ["net"] }
```

:wink:

**Comment by witchof0x20** [comment]
Getting back to this, as I'm more free now. As I understand it, I would modify `tokio_udev::Inner` such that it wraps `AsyncFd<MonitorSocket>` (with an `AsRawFd` trait implementation that's just a wrapper for `MonitorSocket::fd`). 

Then, [`AsyncFd::poll_read_ready`](https://docs.rs/tokio/0.3.2/tokio/io/unix/struct.AsyncFd.html#method.poll_read_ready) can be used to poll the `MonitorSocket` for availability, pulling events out of it if possible. But that requires a `&mut core::task::Context`, and I'm not sure where to grab that from, as I'm not super familiar with how modern tokio works anymore.

File: tokio-udev/Cargo.toml [hunk 2]
```diff
@@ -12,12 +12,12 @@ documentation = "https://docs.rs/tokio-udev"
...
 mio-udev = { path = "../mio-udev", version = "0.3.0" }
 
 futures-core = "0.3"
-tokio = { version = "0.2", features = ["io-driver"] }
+tokio = { version = ">=0.3.2", features = ["net"] } 
 
 [dev-dependencies]
 futures-util = "0.3"
-tokio = { version = "0.2", features = ["macros"] }
+tokio = { version = "0.3", features = ["macros", "rt-multi-thread"] }
```
Comment (witchof0x20) [inline tokio-udev/Cargo.toml]: needed for `#[tokio::main]` in the example

File: tokio-udev/src/lib.rs [hunk 3]
```diff
@@ -137,41 +136,34 @@ impl Stream for MonitorSocket {
...
-            Some(event) => Poll::Ready(Some(event)),
-            None => {
-                self.io
-                    .clear_read_ready(cx, mio::Ready::readable())
-                    .unwrap();
-                Poll::Pending
+        match self.fd.poll_read_ready(ctx) {
+            Poll::Ready(Ok(mut ready_guard)) => {
+                ready_guard.clear_ready();
+                Poll::Ready(self.fd.get_mut().next())
```
Comment (witchof0x20) [inline tokio-udev/src/lib.rs]: This just pulls the event out of the `MonitorSocket`

File: tokio-udev/src/lib.rs [hunk 4]
```diff
@@ -137,41 +136,34 @@ impl Stream for MonitorSocket {
...
             }
+            Poll::Ready(Err(_)) => Poll::Ready(None),
```
Comment (witchof0x20) [inline tokio-udev/src/lib.rs]: Should we be returning `Poll::Ready(None)` for errors? Not sure here

**Comment by witchof0x20** [comment]
I think I got this working with `AsyncFd`. The example compiles and runs, with some changes to be compatible with updated tokio.

Requesting review from @jeandudey

File: tokio-udev/src/lib.rs (hunk 4 above)
Comment (jeandudey) [reply tokio-udev/src/lib.rs]: We can fix this by changing the `Item` type of the `Stream` implementation to be a `io::Result<mio_udev::Event>` as returning `None` for every error to signal the end of the stream might not be wanted and will hide the error, so yeah, go for it :-)

Comment (witchof0x20) [reply tokio-udev/src/lib.rs]: Sounds good. Since this is technically an API break, would this involve any kind of semver change?

Comment (jeandudey) [reply tokio-udev/src/lib.rs]: We'll have to update the semver, but I can do it once this is merged to publish it directly to crates.io

Comment (witchof0x20) [reply tokio-udev/src/lib.rs]: Fixed this to use the result type

**Review by jeandudey — APPROVED** [review]

**Comment by jeandudey** [comment]
Thanks for your contribution! Will add the changes to the CHANGELOG.md and release a new version as soon as possible.

**Comment by jeandudey** [comment]
Released `0.4.0` of both crates with recent changes and `0.5.0` with udev `0.5`
